// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import AllRecruitmentController from "./all_recruitment_controller"
application.register("all-recruitment", AllRecruitmentController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import MapController from "./map_controller"
application.register("map", MapController)

import MobileMenuController from "./mobile_menu_controller"
application.register("mobile-menu", MobileMenuController)

import RecruitmentController from "./recruitment_controller"
application.register("recruitment", RecruitmentController)

import ResumeController from "./resume_controller"
application.register("resume", ResumeController)

import SearchCompanyToJoinController from "./search_company_to_join_controller"
application.register("search-company-to-join", SearchCompanyToJoinController)

import ToastController from "./toast_controller"
application.register("toast", ToastController)

import OnboardingMapController from "./onboarding_map_controller"
application.register("onboarding-map", OnboardingMapController)
